import enum

class UserRole(str, enum.Enum):
    ADMIN = "ADMIN"
    PLANNER = "PLANNER"
    SUPERVISOR = "SUPERVISOR"
    TIMEKEEPER = "TIMEKEEPER"
    USER = "USER"
    WAREHOUSE = "WAREHOUSE"
    ACCOUNTING = "ACCOUNTING"
    QC_ENGINEER = "QC_ENGINEER"
    QC_TECHNICIAN = "QC_TECHNICIAN"