import enum

class UserRole(str, enum.Enum):
    ADMIN = "ADMIN"
    PLANNER = "PLANNER"
    SUPERVISOR = "SUPERVISOR"
    TIMEKEEPER = "TIMEKEEPER"
    USER = "USER"
    WAREHOUSE = "WAREHOUSE"
    ACCOUNTING = "ACCOUNTING"
    QC_COORDINATOR = "QC_COORDINATOR"
    QC_ASSISTANT = "QC_ASSISTANT"