"""'add_supervision_verification_fields'

Revision ID: 000621745134
Revises: 89a0176de5cc
Create Date: 2026-03-11 15:47:07.677440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000621745134'
down_revision: Union[str, Sequence[str], None] = '89a0176de5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_record_stopwatch_task_id'), 'record_stopwatch', ['task_id'], unique=False)
    op.add_column('sup_record_stopwatch', sa.Column('medidas_tomadas', sa.String(), nullable=True))
    op.add_column('sup_record_stopwatch', sa.Column('area_limpia', sa.Boolean(), nullable=False))
    op.add_column('sup_record_stopwatch', sa.Column('peso_verificado', sa.Boolean(), nullable=False))
    op.add_column('sup_record_stopwatch', sa.Column('selladas', sa.Boolean(), nullable=False))
    op.add_column('sup_record_stopwatch', sa.Column('contenedores_limpios', sa.Boolean(), nullable=False))
    op.add_column('sup_record_stopwatch', sa.Column('informacion_correcta', sa.Boolean(), nullable=False))
    op.add_column('sup_record_stopwatch', sa.Column('etiquetas_correctas', sa.Boolean(), nullable=False))
    op.add_column('sup_record_stopwatch', sa.Column('contenedores_correctos', sa.Boolean(), nullable=False))
    op.add_column('sup_stopwatch', sa.Column('area_limpia', sa.Boolean(), nullable=False))
    op.add_column('sup_stopwatch', sa.Column('peso_verificado', sa.Boolean(), nullable=False))
    op.add_column('sup_stopwatch', sa.Column('selladas', sa.Boolean(), nullable=False))
    op.add_column('sup_stopwatch', sa.Column('contenedores_limpios', sa.Boolean(), nullable=False))
    op.add_column('sup_stopwatch', sa.Column('informacion_correcta', sa.Boolean(), nullable=False))
    op.add_column('sup_stopwatch', sa.Column('etiquetas_correctas', sa.Boolean(), nullable=False))
    op.add_column('sup_stopwatch', sa.Column('contenedores_correctos', sa.Boolean(), nullable=False))
    op.add_column('sup_stopwatch', sa.Column('medidas_tomadas', sa.String(), nullable=True))
    op.create_index(op.f('ix_task_lote'), 'task', ['lote'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_lote'), table_name='task')
    op.drop_column('sup_stopwatch', 'medidas_tomadas')
    op.drop_column('sup_stopwatch', 'contenedores_correctos')
    op.drop_column('sup_stopwatch', 'etiquetas_correctas')
    op.drop_column('sup_stopwatch', 'informacion_correcta')
    op.drop_column('sup_stopwatch', 'contenedores_limpios')
    op.drop_column('sup_stopwatch', 'selladas')
    op.drop_column('sup_stopwatch', 'peso_verificado')
    op.drop_column('sup_stopwatch', 'area_limpia')
    op.drop_column('sup_record_stopwatch', 'contenedores_correctos')
    op.drop_column('sup_record_stopwatch', 'etiquetas_correctas')
    op.drop_column('sup_record_stopwatch', 'informacion_correcta')
    op.drop_column('sup_record_stopwatch', 'contenedores_limpios')
    op.drop_column('sup_record_stopwatch', 'selladas')
    op.drop_column('sup_record_stopwatch', 'peso_verificado')
    op.drop_column('sup_record_stopwatch', 'area_limpia')
    op.drop_column('sup_record_stopwatch', 'medidas_tomadas')
    op.drop_index(op.f('ix_record_stopwatch_task_id'), table_name='record_stopwatch')
    # ### end Alembic commands ###
