"""add_real_time_fields_to_stopwatch

Revision ID: 01ba919d1c29
Revises: 5e16ffad7135
Create Date: 2026-03-25 10:17:28.902483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ba919d1c29'
down_revision: Union[str, Sequence[str], None] = '5e16ffad7135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_stopwatch', sa.Column('real_start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('record_stopwatch', sa.Column('real_end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stopwatch', sa.Column('real_start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stopwatch', sa.Column('real_end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stopwatch', 'real_end_time')
    op.drop_column('stopwatch', 'real_start_time')
    op.drop_column('record_stopwatch', 'real_end_time')
    op.drop_column('record_stopwatch', 'real_start_time')
    # ### end Alembic commands ###
