"""sync_latest_model_changes

Revision ID: 06807494578e
Revises: 26fa43a00a35
Create Date: 2025-09-04 08:27:53.396459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06807494578e'
down_revision: Union[str, Sequence[str], None] = '26fa43a00a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('received_user', sa.String(), nullable=True))
    op.add_column('order', sa.Column('received_date', sa.Date(), nullable=True))
    op.add_column('order', sa.Column('received_quantity', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('missing_quantity', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('submitted_user', sa.String(), nullable=True))
    op.add_column('order', sa.Column('submitted_date', sa.Date(), nullable=True))
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('pending', 'programmed', 'unprogrammed', 'completed', name='orderstatus'),
               nullable=True,
               existing_server_default=sa.text("'unprogrammed'::orderstatus"))
    op.add_column('programming_task', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programming_task', 'created_at')
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('pending', 'programmed', 'unprogrammed', 'completed', name='orderstatus'),
               nullable=False,
               existing_server_default=sa.text("'unprogrammed'::orderstatus"))
    op.drop_column('order', 'submitted_date')
    op.drop_column('order', 'submitted_user')
    op.drop_column('order', 'missing_quantity')
    op.drop_column('order', 'received_quantity')
    op.drop_column('order', 'received_date')
    op.drop_column('order', 'received_user')
    # ### end Alembic commands ###
