"""add_code_automation_rules

Revision ID: 06b228757bc0
Revises: 630486173e2a
Create Date: 2026-04-06 11:58:19.989795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b228757bc0'
down_revision: Union[str, Sequence[str], None] = '630486173e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_automation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('min_quantity', sa.Float(), nullable=True),
    sa.Column('max_quantity', sa.Float(), nullable=True),
    sa.Column('target_team_id', sa.UUID(), nullable=False),
    sa.Column('overflow_team_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['code.id'], ),
    sa.ForeignKeyConstraint(['overflow_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['target_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_automation_rules_id'), 'code_automation_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_automation_rules_id'), table_name='code_automation_rules')
    op.drop_table('code_automation_rules')
    # ### end Alembic commands ###
