"""create qc_manual table

Revision ID: 0a25ced99a18
Revises: 5150cc4a090f
Create Date: 2025-12-22 11:15:36.789147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a25ced99a18'
down_revision: Union[str, Sequence[str], None] = '5150cc4a090f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qc_manual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_manual_id'), 'qc_manual', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qc_manual_id'), table_name='qc_manual')
    op.drop_table('qc_manual')
    # ### end Alembic commands ###
