"""Detect and apply new changes

Revision ID: 0c7411572b18
Revises: 36be1e0e135b
Create Date: 2026-01-24 10:54:47.776086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7411572b18'
down_revision: Union[str, Sequence[str], None] = '36be1e0e135b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if is_hidden column already exists in order table
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    order_columns = [c['name'] for c in inspector.get_columns('order')]
    if 'is_hidden' not in order_columns:
        op.add_column('order', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    
    # Check if ix_qc_manual_name index exists before dropping
    indices = inspector.get_indexes('qc_manual')
    if any(ix['name'] == 'ix_qc_manual_name' for ix in indices):
        op.drop_index(op.f('ix_qc_manual_name'), table_name='qc_manual')
    
    # Check if name column exists in qc_manual before dropping
    qc_manual_columns = [c['name'] for c in inspector.get_columns('qc_manual')]
    if 'name' in qc_manual_columns:
        op.drop_column('qc_manual', 'name')
        
    op.alter_column('test_record', 'catalog_test',
               existing_type=sa.UUID(),
               nullable=False)
    
    if 'code_id' in [c['name'] for c in inspector.get_columns('test_record')]:
        op.drop_column('test_record', 'code_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_record', sa.Column('code_id', sa.UUID(), autoincrement=False, nullable=True))
    op.alter_column('test_record', 'catalog_test',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('qc_manual', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_qc_manual_name'), 'qc_manual', ['name'], unique=False)
    op.drop_column('order', 'is_hidden')
    # ### end Alembic commands ###
