"""Detect and apply new changes

Revision ID: 0c7411572b18
Revises: 36be1e0e135b
Create Date: 2026-01-24 10:54:47.776086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7411572b18'
down_revision: Union[str, Sequence[str], None] = '36be1e0e135b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_qc_manual_name'), table_name='qc_manual')
    op.drop_column('qc_manual', 'name')
    op.alter_column('test_record', 'catalog_test',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('test_record', 'code_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_record', sa.Column('code_id', sa.UUID(), autoincrement=False, nullable=True))
    op.alter_column('test_record', 'catalog_test',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('qc_manual', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_qc_manual_name'), 'qc_manual', ['name'], unique=False)
    op.drop_column('order', 'is_hidden')
    # ### end Alembic commands ###
