"""sync models: programming_task real fields, task fields, code fields, etc.

Revision ID: 1253753fbd69
Revises: 80035a09fb8d
Create Date: 2025-07-22 16:15:45.406193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1253753fbd69'
down_revision: Union[str, Sequence[str], None] = '80035a09fb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programming_task', sa.Column('real_start_time', sa.DateTime(), nullable=True))
    op.add_column('programming_task', sa.Column('real_end_time', sa.DateTime(), nullable=True))
    op.add_column('programming_task', sa.Column('real_quantity', sa.Integer(), nullable=True))
    op.add_column('programming_task', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('programming_task', sa.Column('completed_by_user_id', sa.UUID(), nullable=True))
    op.alter_column('programming_task', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('programming_task', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'programming_task', 'users', ['completed_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'programming_task', type_='foreignkey')
    op.alter_column('programming_task', 'end_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('programming_task', 'start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('programming_task', 'completed_by_user_id')
    op.drop_column('programming_task', 'comment')
    op.drop_column('programming_task', 'real_quantity')
    op.drop_column('programming_task', 'real_end_time')
    op.drop_column('programming_task', 'real_start_time')
    # ### end Alembic commands ###
