"""quality_test_models

Revision ID: 23bdd10ea6bb
Revises: 9410975b2cf0
Create Date: 2025-12-18 10:21:29.796288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23bdd10ea6bb'
down_revision: Union[str, Sequence[str], None] = '9410975b2cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_test',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('open', 'close', 'both', name='type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_test',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_id', sa.UUID(), nullable=False),
    sa.Column('catalog_test_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_test_id'], ['catalog_test.id'], ),
    sa.ForeignKeyConstraint(['code_id'], ['code.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lote', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('done', 'undone', 'accepted', 'pending', name='teststatus'), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lote'], ['order.lote'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_team_association')
    op.add_column('historico_comparacion_fechas', sa.Column('fecha', sa.DateTime(), nullable=False))
    op.drop_column('historico_comparacion_fechas', 'date')
    op.add_column('history_comparison', sa.Column('numero_personas', sa.Integer(), nullable=True))
    op.alter_column('history_comparison', 'diferencia',
               existing_type=sa.NUMERIC(precision=7, scale=3),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.add_column('users', sa.Column('signature', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'signature')
    op.alter_column('history_comparison', 'diferencia',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=7, scale=3),
               existing_nullable=True)
    op.drop_column('history_comparison', 'numero_personas')
    op.add_column('historico_comparacion_fechas', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('historico_comparacion_fechas', 'fecha')
    op.create_table('user_team_association',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('user_team_association_team_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_team_association_user_id_fkey'))
    )
    op.drop_table('test')
    op.drop_table('code_test')
    op.drop_table('catalog_test')
    # ### end Alembic commands ###
