"""Add code_test_parameter_specification table

Revision ID: 2807c6534ac9
Revises: b08e07d3b575
Create Date: 2026-02-13 08:52:04.821292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2807c6534ac9'
down_revision: Union[str, Sequence[str], None] = 'b08e07d3b575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_test_parameter_specification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('specification', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['code.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['catalog_test_question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_test_parameter_specification_code_id'), 'code_test_parameter_specification', ['code_id'], unique=False)
    op.create_index(op.f('ix_code_test_parameter_specification_question_id'), 'code_test_parameter_specification', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_test_parameter_specification_question_id'), table_name='code_test_parameter_specification')
    op.drop_index(op.f('ix_code_test_parameter_specification_code_id'), table_name='code_test_parameter_specification')
    op.drop_table('code_test_parameter_specification')
    # ### end Alembic commands ###
