"""update role enum

Revision ID: 280a1cd0bb63
Revises: a5f8fff2afbe
Create Date: 2025-10-24 11:28:04.356697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280a1cd0bb63'
down_revision: Union[str, Sequence[str], None] = 'a5f8fff2afbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('code_service_id_fkey'), 'code', 'services', ['service_id'], ['id'])
    op.alter_column('code', 'quantity',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('code', 'activity')
    op.drop_column('code', 'type')
    op.create_table('services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('services_pkey'))
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_code'), 'services', ['code'], unique=True)
    # ### end Alembic commands ###
