"""Change accumulated_duration to Float in Stopwatch and RecordStopwatch models and schemas

Revision ID: 2fc5054b4cb7
Revises: acf483298c17
Create Date: 2025-10-31 14:17:14.086490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc5054b4cb7'
down_revision: Union[str, Sequence[str], None] = 'acf483298c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
