"""initial migration

Revision ID: 3096d60d88d7
Revises: 
Create Date: 2025-09-22 08:32:44.688897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3096d60d88d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('people', sa.Integer(), nullable=True),
    sa.Column('performance', sa.Float(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('presentation', sa.String(), nullable=True),
    sa.Column('fabricationCode', sa.String(), nullable=True),
    sa.Column('usefulLife', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('lote', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('dueDate', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('bin', sa.Integer(), nullable=True),
    sa.Column('received_user', sa.String(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('received_quantity', sa.Integer(), nullable=True),
    sa.Column('missing_quantity', sa.Integer(), nullable=True),
    sa.Column('submitted_user', sa.String(), nullable=True),
    sa.Column('submitted_date', sa.Date(), nullable=True),
    sa.Column('submitted_observations', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('lote')
    )
    op.create_table('preparation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PLANNER', 'SUPERVISOR', 'USER', 'WAREHOUSE', name='userrole'), nullable=True),
    sa.Column('state', sa.Enum('ACTIVE', 'INACTIVE', name='userstate'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_id', sa.UUID(), nullable=True),
    sa.Column('preparation_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('lote', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('specification', sa.String(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('people', sa.Integer(), nullable=True),
    sa.Column('performance', sa.Float(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('presentation', sa.String(), nullable=True),
    sa.Column('fabricationCode', sa.String(), nullable=True),
    sa.Column('usefulLife', sa.String(), nullable=True),
    sa.Column('related_task_code', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['code.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['preparation_id'], ['preparation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('supervisorId', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['supervisorId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('programming',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('available', 'unavailable', name='programmingstatus'), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'team_id', name='_date_team_uc')
    )
    op.create_table('task_team_association',
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], )
    )
    op.create_table('user_team_association',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('programming_task',
    sa.Column('programming_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('real_start_time', sa.DateTime(), nullable=True),
    sa.Column('real_end_time', sa.DateTime(), nullable=True),
    sa.Column('real_quantity', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('completed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['programming_id'], ['programming.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('programming_id', 'task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programming_task')
    op.drop_table('user_team_association')
    op.drop_table('task_team_association')
    op.drop_table('programming')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('task')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('preparation')
    op.drop_table('order')
    op.drop_table('code')
    # ### end Alembic commands ###
