"""Add warehouse history table

Revision ID: 3586d4de1176
Revises: fix_lowercase_roles
Create Date: 2026-01-12 09:19:22.614672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3586d4de1176'
down_revision: Union[str, Sequence[str], None] = 'fix_lowercase_roles'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lote', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('SENT', 'RECEIVED', 'TRANSFER_SOURCE', 'TRANSFER_TARGET', name='warehousehistorytype'), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('observations', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lote'], ['order.lote'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse_history')
    # ### end Alembic commands ###
