"""Add order_surplus table

Revision ID: 36be1e0e135b
Revises: 3332f46ab036
Create Date: 2026-01-24 10:06:05.694565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36be1e0e135b'
down_revision: Union[str, Sequence[str], None] = '3332f46ab036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_surplus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lote', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('original_quantity', sa.Float(), nullable=False),
    sa.Column('received_quantity', sa.Float(), nullable=False),
    sa.Column('surplus', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lote'], ['order.lote'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Note: do not drop 'daily_available' here — keep existing table
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrade: remove only the table added in upgrade
    op.drop_table('order_surplus')
    # ### end Alembic commands ###
