"""new table stopwatch

Revision ID: 3714b5e23592
Revises: 73604d9579f8
Create Date: 2025-11-18 13:50:50.353759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3714b5e23592'
down_revision: Union[str, Sequence[str], None] = '73604d9579f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    taskstatus_enum = sa.Enum('PENDING', 'ACTIVE', 'PAUSED', 'COMPLETED', name='taskstatus')
    taskstatus_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('record_stopwatch', sa.Column('comments', sa.String(), nullable=True))
    op.alter_column('task_status_log', 'status',
               existing_type=sa.VARCHAR(),
               type_=taskstatus_enum,
               existing_nullable=False,
               postgresql_using='status::taskstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_status_log', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'PAUSED', 'COMPLETED', name='taskstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='status::text')
    op.drop_column('record_stopwatch', 'comments')
    taskstatus_enum = sa.Enum('PENDING', 'ACTIVE', 'PAUSED', 'COMPLETED', name='taskstatus')
    taskstatus_enum.drop(op.get_bind())
    # ### end Alembic commands ###
