"""Add verification column to code table

Revision ID: 381f5472f6a7
Revises: e2a2b4ccacce
Create Date: 2026-03-09 10:26:04.118015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381f5472f6a7'
down_revision: Union[str, Sequence[str], None] = 'e2a2b4ccacce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('verification', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code', 'verification')
    # ### end Alembic commands ###
