"""add code verification table

Revision ID: 3e1f35281e87
Revises: 79c806f001db
Create Date: 2026-03-23 12:14:29.635069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1f35281e87'
down_revision: Union[str, Sequence[str], None] = '79c806f001db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_verification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codeId', sa.UUID(), nullable=True),
    sa.Column('userId', sa.UUID(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['codeId'], ['code.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_verification')
    # ### end Alembic commands ###
