"""add_indexes_to_performance_critical_columns

Revision ID: 4167aec26642
Revises: 7f577601566e
Create Date: 2026-03-20 15:04:04.782510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4167aec26642'
down_revision: Union[str, Sequence[str], None] = '7f577601566e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_code_code'), 'code', ['code'], unique=False)
    op.create_index(op.f('ix_code_fabricationCode'), 'code', ['fabricationCode'], unique=False)
    op.create_index(op.f('ix_order_code'), 'order', ['code'], unique=False)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_index(op.f('ix_programming_status'), 'programming', ['status'], unique=False)
    op.create_index(op.f('ix_task_activity'), 'task', ['activity'], unique=False)
    op.create_index(op.f('ix_task_fabricationCode'), 'task', ['fabricationCode'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_type'), 'task', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_type'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_fabricationCode'), table_name='task')
    op.drop_index(op.f('ix_task_activity'), table_name='task')
    op.drop_index(op.f('ix_programming_status'), table_name='programming')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_code'), table_name='order')
    op.drop_index(op.f('ix_code_fabricationCode'), table_name='code')
    op.drop_index(op.f('ix_code_code'), table_name='code')
    # ### end Alembic commands ###
