"""remove_user_state_column

Revision ID: 42b009fef5cd
Revises: 4167aec26642
Create Date: 2026-03-21 08:44:08.172871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42b009fef5cd'
down_revision: Union[str, Sequence[str], None] = '4167aec26642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('state', postgresql.ENUM('ACTIVE', 'INACTIVE', name='userstate'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
