"""Add extra optional fields to Task model

Revision ID: 4ad8e3a43963
Revises: 1b2c129304d8
Create Date: 2025-07-18 08:09:50.310707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad8e3a43963'
down_revision: Union[str, Sequence[str], None] = '1b2c129304d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('people', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('performance', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('material', sa.String(), nullable=True))
    op.add_column('task', sa.Column('presentation', sa.String(), nullable=True))
    op.add_column('task', sa.Column('fabricationCode', sa.String(), nullable=True))
    op.add_column('task', sa.Column('usefulLife', sa.String(), nullable=True))
    op.add_column('task', sa.Column('related_task_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'related_task_code')
    op.drop_column('task', 'usefulLife')
    op.drop_column('task', 'fabricationCode')
    op.drop_column('task', 'presentation')
    op.drop_column('task', 'material')
    op.drop_column('task', 'performance')
    op.drop_column('task', 'people')
    # ### end Alembic commands ###
