"""add auto_created and created_at fields to task

Revision ID: 4ca9a42284bd
Revises: 9d8a7c301057
Create Date: 2025-09-02 15:26:40.520768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca9a42284bd'
down_revision: Union[str, Sequence[str], None] = '9d8a7c301057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
