"""update qc_manual

Revision ID: 4f35bce32684
Revises: 0a25ced99a18
Create Date: 2025-12-22 13:52:25.598434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f35bce32684'
down_revision: Union[str, Sequence[str], None] = '0a25ced99a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qc_manual', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qc_manual', 'createdAt')
    # ### end Alembic commands ###
