"""add manual_section_id to catalog_test

Revision ID: 5150cc4a090f
Revises: c3dec41cf904
Create Date: 2025-12-22 10:45:57.846252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5150cc4a090f'
down_revision: Union[str, Sequence[str], None] = 'c3dec41cf904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_test', sa.Column('manual_section_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_test', 'manual_section_id')
    # ### end Alembic commands ###
