"""update order status enum to add programada and remove unprogrammed

Revision ID: 53520c8b742b
Revises: 885045653df4
Create Date: 2025-07-23 15:03:52.722529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53520c8b742b'
down_revision: Union[str, Sequence[str], None] = '885045653df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Asegúrate de que 'UNPROGRAMMED' y 'PROGRAMADA' existen en el ENUM
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'UNPROGRAMMED'")
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'unprogrammed'")
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'PROGRAMADA'")
    # 2. Cambia las órdenes con 'UNPROGRAMMED' o 'unprogrammed' a 'PENDING'
    op.execute("UPDATE \"order\" SET status = 'PENDING' WHERE status = 'UNPROGRAMMED' OR status = 'unprogrammed'")
    # 3. Renombra y recrea el ENUM sin 'UNPROGRAMMED' ni 'unprogrammed'
    op.execute("ALTER TYPE orderstatus RENAME TO orderstatus_old")
    op.execute("CREATE TYPE orderstatus AS ENUM('PENDING', 'PROGRAMADA', 'IN_PROGRESS', 'COMPLETED')")
    op.execute("ALTER TABLE \"order\" ALTER COLUMN status TYPE orderstatus USING status::text::orderstatus")
    op.execute("DROP TYPE orderstatus_old")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'unprogrammed'")
    op.execute("ALTER TYPE orderstatus RENAME TO orderstatus_new")
    op.execute("CREATE TYPE orderstatus AS ENUM('pending', 'in_progress', 'completed', 'unprogrammed')")
    op.execute("ALTER TABLE \"order\" ALTER COLUMN status TYPE orderstatus USING status::text::orderstatus")
    op.execute("DROP TYPE orderstatus_new")
    # ### end Alembic commands ###
