"""Add verificacion_utensilios to supervision

Revision ID: 5a03b688af54
Revises: c2a8d8ff0b4a
Create Date: 2026-03-16 14:11:37.240696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a03b688af54'
down_revision: Union[str, Sequence[str], None] = 'c2a8d8ff0b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sup_record_stopwatch', sa.Column('verificacion_utensilios', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('sup_stopwatch', sa.Column('verificacion_utensilios', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sup_stopwatch', 'verificacion_utensilios')
    op.drop_column('sup_record_stopwatch', 'verificacion_utensilios')
    op.create_table('sup_task_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sup_task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('observation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sup_task_id'], ['sup_task.id'], name=op.f('sup_task_history_sup_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sup_task_history_pkey'))
    )
    op.create_table('sup_task',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sup_task_pkey'))
    )
    # ### end Alembic commands ###
