"""Add ProductionCode table

Revision ID: 630486173e2a
Revises: a59e91699c6a
Create Date: 2026-03-27 12:18:06.754392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630486173e2a'
down_revision: Union[str, Sequence[str], None] = 'a59e91699c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_code',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('people', sa.Integer(), nullable=True),
    sa.Column('performance', sa.Float(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('presentation', sa.String(), nullable=True),
    sa.Column('fabricationCode', sa.String(), nullable=True),
    sa.Column('usefulLife', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_code_code'), 'production_code', ['code'], unique=False)
    op.create_index(op.f('ix_production_code_fabricationCode'), 'production_code', ['fabricationCode'], unique=False)
    op.drop_table('equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('equipment_pkey'))
    )
    op.drop_index(op.f('ix_production_code_fabricationCode'), table_name='production_code')
    op.drop_index(op.f('ix_production_code_code'), table_name='production_code')
    op.drop_table('production_code')
    # ### end Alembic commands ###
