"""add duration_in_hours to programming_task

Revision ID: 73604d9579f8
Revises: b7fae0c6d8c7
Create Date: 2025-11-04 13:39:20.098254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73604d9579f8'
down_revision: Union[str, Sequence[str], None] = 'b7fae0c6d8c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programming_task', sa.Column('duration_in_hours', sa.Float(), nullable=True))
    op.add_column('stopwatch', sa.Column('is_from_programming', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stopwatch', 'is_from_programming')
    op.drop_column('programming_task', 'duration_in_hours')
    # ### end Alembic commands ###
