"""remove_verification_from_code

Revision ID: 79c806f001db
Revises: b8747ea43942
Create Date: 2026-03-23 11:23:14.376070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c806f001db'
down_revision: Union[str, Sequence[str], None] = 'b8747ea43942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code', 'verification')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('verification', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
