"""Check for pending model changes

Revision ID: 7b6dd203d7ca
Revises: 4ad8e3a43963
Create Date: 2025-07-18 11:09:09.772258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6dd203d7ca'
down_revision: Union[str, Sequence[str], None] = '4ad8e3a43963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programming_id'), table_name='programming')
    op.alter_column('programming_task', 'programming_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('programming_task', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('programming_task', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('programming_task', 'programming_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_programming_id'), 'programming', ['id'], unique=False)
    # ### end Alembic commands ###
