"""Add special_codes table

Revision ID: 7f577601566e
Revises: 5a03b688af54
Create Date: 2026-03-20 11:41:27.830723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f577601566e'
down_revision: Union[str, Sequence[str], None] = '5a03b688af54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('special_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('programming_code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_special_codes_code'), 'special_codes', ['code'], unique=True)
    op.drop_table('sup_task_history')
    op.drop_table('sup_task')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sup_task',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sup_task_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('sup_task_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sup_task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('observation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sup_task_id'], ['sup_task.id'], name=op.f('sup_task_history_sup_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sup_task_history_pkey'))
    )
    op.drop_index(op.f('ix_special_codes_code'), table_name='special_codes')
    op.drop_table('special_codes')
    op.drop_table('equipment')
    # ### end Alembic commands ###
