"""fix_catalog_test_relationship_and_imports

Revision ID: 82cb6c0b8b2d
Revises: f95c7a5f15ce
Create Date: 2026-01-28 11:49:09.258981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82cb6c0b8b2d'
down_revision: Union[str, Sequence[str], None] = 'f95c7a5f15ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_test', sa.Column('chapter_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_catalog_test_chapter_id'), 'catalog_test', ['chapter_id'], unique=False)
    op.create_foreign_key(None, 'catalog_test', 'qc_manual_chapter', ['chapter_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalog_test', type_='foreignkey')
    op.drop_index(op.f('ix_catalog_test_chapter_id'), table_name='catalog_test')
    op.drop_column('catalog_test', 'chapter_id')
    # ### end Alembic commands ###
