"""add programming model and programming_task association

Revision ID: 839e1a19dfc0
Revises: f391dfcea71f
Create Date: 2025-07-17 11:04:16.793771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839e1a19dfc0'
down_revision: Union[str, Sequence[str], None] = 'f391dfcea71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
