"""add is_completed to programming_task

Revision ID: 885045653df4
Revises: 1253753fbd69
Create Date: 2025-07-23 14:25:52.371593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885045653df4'
down_revision: Union[str, Sequence[str], None] = '1253753fbd69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programming_task', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programming_task', 'is_completed')
    # ### end Alembic commands ###
