"""Add supervision models

Revision ID: 89a0176de5cc
Revises: 381f5472f6a7
Create Date: 2026-03-11 15:26:35.007693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89a0176de5cc'
down_revision: Union[str, Sequence[str], None] = '381f5472f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sup_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sup_task_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sup_task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('observation', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sup_task_id'], ['sup_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sup_record_stopwatch',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('supervisor_id', sa.UUID(), nullable=False),
    sa.Column('accumulated_duration', sa.Float(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sup_record_stopwatch_task_id'), 'sup_record_stopwatch', ['task_id'], unique=False)
    op.create_table('sup_stopwatch',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('supervisor_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('RUNNING', 'PAUSED', 'STOPPED', name='timerstatus', create_type=False), nullable=False),
    sa.Column('accumulated_duration', sa.Float(), nullable=False),
    sa.Column('real_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('real_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sup_stopwatch')
    op.drop_index(op.f('ix_sup_record_stopwatch_task_id'), table_name='sup_record_stopwatch')
    op.drop_table('sup_record_stopwatch')
    op.drop_table('sup_task_history')
    op.drop_table('sup_task')
    # ### end Alembic commands ###
