"""Add task creation notification table

Revision ID: 9410975b2cf0
Revises: 3d6f805acb67
Create Date: 2025-12-11 08:06:11.490651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9410975b2cf0'
down_revision: Union[str, Sequence[str], None] = '3d6f805acb67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_creation_notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('programming_info', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_creation_notification')
    # ### end Alembic commands ###
