"""empty message

Revision ID: 979439832514
Revises: c4812b0ecaa0
Create Date: 2025-12-30 09:27:54.037885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979439832514'
down_revision: Union[str, Sequence[str], None] = 'c4812b0ecaa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('test_lote_key'), 'test', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('test_lote_key'), 'test', ['lote'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
