"""Add ProgrammingTask association object with order and times

Revision ID: 9b4e98293d74
Revises: 7b6dd203d7ca
Create Date: 2025-07-18 14:24:01.228490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4e98293d74'
down_revision: Union[str, Sequence[str], None] = '7b6dd203d7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programming_task', sa.Column('order', sa.Integer(), nullable=False))
    op.add_column('programming_task', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('programming_task', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.alter_column('programming_task', 'programming_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('programming_task', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('programming_task', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('programming_task', 'programming_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('programming_task', 'end_time')
    op.drop_column('programming_task', 'start_time')
    op.drop_column('programming_task', 'order')
    # ### end Alembic commands ###
