"""sync_models_with_latest_changes

Revision ID: 9d8a7c301057
Revises: c05b1a8883ca
Create Date: 2025-08-22 10:14:48.080018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8a7c301057'
down_revision: Union[str, Sequence[str], None] = 'c05b1a8883ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code', 'related_code_team')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('related_code_team', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
