"""update_models

Revision ID: a1ade86f6e6d
Revises: b743835ec206
Create Date: 2026-02-05 13:48:07.323154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ade86f6e6d'
down_revision: Union[str, Sequence[str], None] = 'b743835ec206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('catalog_test_question_catalog_test_id_fkey'), 'catalog_test_question', type_='foreignkey')
    op.create_foreign_key(None, 'catalog_test_question', 'catalog_test', ['catalog_test_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('code_test_catalog_test_id_fkey'), 'code_test', type_='foreignkey')
    op.create_foreign_key(None, 'code_test', 'catalog_test', ['catalog_test_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('test_results_catalog_test_id_fkey'), 'test_results', type_='foreignkey')
    op.create_foreign_key(None, 'test_results', 'catalog_test', ['catalog_test_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_results', type_='foreignkey')
    op.create_foreign_key(op.f('test_results_catalog_test_id_fkey'), 'test_results', 'catalog_test', ['catalog_test_id'], ['id'])
    op.drop_constraint(None, 'code_test', type_='foreignkey')
    op.create_foreign_key(op.f('code_test_catalog_test_id_fkey'), 'code_test', 'catalog_test', ['catalog_test_id'], ['id'])
    op.drop_constraint(None, 'catalog_test_question', type_='foreignkey')
    op.create_foreign_key(op.f('catalog_test_question_catalog_test_id_fkey'), 'catalog_test_question', 'catalog_test', ['catalog_test_id'], ['id'])
    # ### end Alembic commands ###
