"""apply_model_changes

Revision ID: a86a9dc280d1
Revises: 82cb6c0b8b2d
Create Date: 2026-01-29 11:03:15.017204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a86a9dc280d1'
down_revision: Union[str, Sequence[str], None] = '82cb6c0b8b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_manual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_manual_id'), 'quality_manual', ['id'], unique=False)
    op.create_index(op.f('ix_quality_manual_name'), 'quality_manual', ['name'], unique=True)
    op.create_table('qc_manual_chapter',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manual_id', sa.Integer(), nullable=False),
    sa.Column('parent_chapter_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('chapter_type', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['manual_id'], ['qc_manual.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_chapter_id'], ['qc_manual_chapter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_manual_chapter_manual_id'), 'qc_manual_chapter', ['manual_id'], unique=False)
    op.create_index(op.f('ix_qc_manual_chapter_parent_chapter_id'), 'qc_manual_chapter', ['parent_chapter_id'], unique=False)
    op.drop_table('order_surplus')
    op.add_column('catalog_test', sa.Column('quality_manual_id', sa.Integer(), nullable=True))
    op.add_column('catalog_test', sa.Column('chapter_id', sa.UUID(), nullable=True))
    op.alter_column('catalog_test', 'chapter',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'General'::character varying"))
    op.create_index(op.f('ix_catalog_test_chapter_id'), 'catalog_test', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_catalog_test_quality_manual_id'), 'catalog_test', ['quality_manual_id'], unique=False)
    op.create_foreign_key(None, 'catalog_test', 'quality_manual', ['quality_manual_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'catalog_test', 'qc_manual_chapter', ['chapter_id'], ['id'], ondelete='SET NULL')
    op.add_column('catalog_test_question', sa.Column('chapter_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_catalog_test_question_chapter_id'), 'catalog_test_question', ['chapter_id'], unique=False)
    op.create_foreign_key(None, 'catalog_test_question', 'qc_manual_chapter', ['chapter_id'], ['id'], ondelete='SET NULL')
    op.drop_column('order', 'is_hidden')
    op.add_column('qc_manual', sa.Column('quality_manual_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_qc_manual_quality_manual_id'), 'qc_manual', ['quality_manual_id'], unique=False)
    op.create_foreign_key(None, 'qc_manual', 'quality_manual', ['quality_manual_id'], ['id'], ondelete='CASCADE')
    op.drop_column('qc_manual', 'version')
    op.drop_column('qc_manual', 'content')
    op.add_column('test_record', sa.Column('code_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('test_record_catalog_test_fkey'), 'test_record', type_='foreignkey')
    op.create_foreign_key(None, 'test_record', 'code', ['code_id'], ['id'])
    op.drop_column('test_record', 'catalog_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_record', sa.Column('catalog_test', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('test_record_code_id_fkey', 'test_record', type_='foreignkey')
    op.create_foreign_key(op.f('test_record_catalog_test_fkey'), 'test_record', 'catalog_test', ['catalog_test'], ['id'])
    op.drop_column('test_record', 'code_id')
    op.add_column('qc_manual', sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('qc_manual', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('qc_manual_quality_manual_id_fkey', 'qc_manual', type_='foreignkey')
    op.drop_index(op.f('ix_qc_manual_quality_manual_id'), table_name='qc_manual')
    op.drop_column('qc_manual', 'quality_manual_id')
    op.add_column('order', sa.Column('is_hidden', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint('catalog_test_question_chapter_id_fkey', 'catalog_test_question', type_='foreignkey')
    op.drop_index(op.f('ix_catalog_test_question_chapter_id'), table_name='catalog_test_question')
    op.drop_column('catalog_test_question', 'chapter_id')
    op.drop_constraint('catalog_test_quality_manual_id_fkey', 'catalog_test', type_='foreignkey')
    op.drop_constraint('catalog_test_chapter_id_fkey', 'catalog_test', type_='foreignkey')
    op.drop_index(op.f('ix_catalog_test_quality_manual_id'), table_name='catalog_test')
    op.drop_index(op.f('ix_catalog_test_chapter_id'), table_name='catalog_test')
    op.alter_column('catalog_test', 'chapter',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'General'::character varying"))
    op.drop_column('catalog_test', 'chapter_id')
    op.drop_column('catalog_test', 'quality_manual_id')
    op.create_table('order_surplus',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lote', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('original_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('received_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('surplus', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lote'], ['order.lote'], name=op.f('order_surplus_lote_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_surplus_pkey'))
    )
    op.drop_index(op.f('ix_qc_manual_chapter_parent_chapter_id'), table_name='qc_manual_chapter')
    op.drop_index(op.f('ix_qc_manual_chapter_manual_id'), table_name='qc_manual_chapter')
    op.drop_table('qc_manual_chapter')
    op.drop_index(op.f('ix_quality_manual_name'), table_name='quality_manual')
    op.drop_index(op.f('ix_quality_manual_id'), table_name='quality_manual')
    op.drop_table('quality_manual')
    # ### end Alembic commands ###
