"""Change accumulated_duration to Float in Stopwatch and RecordStopwatch models and schemas

Revision ID: acf483298c17
Revises: ee9ab5e60be0
Create Date: 2025-10-31 14:04:33.743618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf483298c17'
down_revision: Union[str, Sequence[str], None] = 'ee9ab5e60be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
