"""add created_by_user_id to task

Revision ID: add_created_by_user_id_to_task
Revises: e4fd39ab5b1f
Create Date: 2024-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_created_by_user_id_to_task'
down_revision = 'e4fd39ab5b1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_by_user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'task', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'created_by_user_id')
    # ### end Alembic commands ### 