"""add_analysis_number_to_test_record

Revision ID: afe5f118a05f
Revises: c6a6cc1e9d8d
Create Date: 2026-02-02 10:10:06.044606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe5f118a05f'
down_revision: Union[str, Sequence[str], None] = 'c6a6cc1e9d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_record', sa.Column('analysis_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_record', 'analysis_number')
    # ### end Alembic commands ###
