"""add_options_to_catalog_test_question

Revision ID: b08e07d3b575
Revises: 56ae1062052b
Create Date: 2026-02-09 09:29:43.389770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08e07d3b575'
down_revision: Union[str, Sequence[str], None] = '56ae1062052b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table daily_available already exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'daily_available' not in existing_tables:
        op.create_table('daily_available',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('codigo', sa.String(length=20), nullable=True),
        sa.Column('description', sa.String(length=80), nullable=True),
        sa.Column('disponible', sa.Integer(), nullable=True),
        sa.Column('minimo', sa.Integer(), nullable=True),
        sa.Column('reorder', sa.Integer(), nullable=True),
        sa.Column('dias_disponibles', sa.Integer(), nullable=True),
        sa.Column('date_upload', sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    
    # Check if column options already exists in catalog_test_question
    existing_columns = [col['name'] for col in inspector.get_columns('catalog_test_question')]
    if 'options' not in existing_columns:
        op.add_column('catalog_test_question', sa.Column('options', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_test_question', 'options')
    op.drop_table('daily_available')
    # ### end Alembic commands ###
