"""add creation_date to record_stopwatch

Revision ID: b7fae0c6d8c7
Revises: d0c13ee0ed78
Create Date: 2025-11-04 09:58:28.882058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7fae0c6d8c7'
down_revision: Union[str, Sequence[str], None] = 'd0c13ee0ed78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_stopwatch', sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('task_status_log', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_status_log', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('record_stopwatch', 'creation_date')
    # ### end Alembic commands ###
