"""add_users_profiles_table_remove_profile_cols_from_users

Revision ID: b8747ea43942
Revises: 42b009fef5cd
Create Date: 2026-03-21 08:55:27.748148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8747ea43942'
down_revision: Union[str, Sequence[str], None] = '42b009fef5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('role', postgresql.ENUM(name='userrole', create_type=False), nullable=False),
    sa.Column('signature', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_profiles_id'), 'users_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_users_profiles_user_id'), 'users_profiles', ['user_id'], unique=True)

    # ---- Data migration: copy existing profile data from users ----
    conn = op.get_bind()
    conn.execute(
        sa.text("""
            INSERT INTO users_profiles (id, user_id, full_name, cargo, role, signature)
            SELECT gen_random_uuid(), id, full_name, cargo,
                   COALESCE(role::text, 'USER')::"userrole",
                   signature
            FROM users
        """)
    )
    # ----------------------------------------------------------------

    op.drop_column('users', 'role')
    op.drop_column('users', 'document_name')
    op.drop_column('users', 'signature')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'cargo')
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cargo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('signature', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('document_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('role', postgresql.ENUM('ADMIN', 'PLANNER', 'SUPERVISOR', 'USER', 'WAREHOUSE', 'ACCOUNTING', 'TIMEKEEPER', 'QC_ENGINEER', 'QC_TECHNICIAN', 'QC_COORDINATOR', 'QC_ASSISTANT', name='userrole'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_profiles_user_id'), table_name='users_profiles')
    op.drop_index(op.f('ix_users_profiles_id'), table_name='users_profiles')
    op.drop_table('users_profiles')
    # ### end Alembic commands ###
