"""sync_models_with_current_schema

Revision ID: c05b1a8883ca
Revises: f2e584f6e39b
Create Date: 2025-08-22 10:01:36.986659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c05b1a8883ca'
down_revision: Union[str, Sequence[str], None] = 'f2e584f6e39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_team_association')
    
    # Create the ProgrammingStatus enum type
    programmingstatus_enum = postgresql.ENUM('available', 'unavailable', name='programmingstatus')
    programmingstatus_enum.create(op.get_bind())
    
    op.add_column('programming', sa.Column('status', sa.Enum('available', 'unavailable', name='programmingstatus'), nullable=False, server_default='available'))
    op.alter_column('programming_task', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('programming_task', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # Convert quantity from VARCHAR to INTEGER with proper casting
    op.execute("UPDATE task SET quantity = CASE WHEN quantity ~ '^[0-9]+$' THEN quantity::integer ELSE NULL END")
    op.alter_column('task', 'quantity',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='quantity::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='quantity::varchar')
    op.alter_column('programming_task', 'end_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('programming_task', 'start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('programming', 'status')
    
    # Drop the ProgrammingStatus enum type
    programmingstatus_enum = postgresql.ENUM(name='programmingstatus')
    programmingstatus_enum.drop(op.get_bind())
    
    op.create_table('code_team_association',
    sa.Column('code_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['code.id'], name=op.f('code_team_association_code_id_fkey')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('code_team_association_team_id_fkey'))
    )
    # ### end Alembic commands ###
