"""add_timezone_to_programming_task_start_time_and_end_time

Revision ID: c1608e1076b5
Revises: fix_order_status_enum_case
Create Date: 2025-08-18 09:06:50.175833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1608e1076b5'
down_revision: Union[str, Sequence[str], None] = 'fix_order_status_enum_case'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'status_tmp')
    # Omitir el cambio de tipo de quantity por ahora
    # op.alter_column('task', 'quantity',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    
    # Agregar timezone a programming_task
    op.alter_column('programming_task', 'start_time',
               existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('programming_task', 'end_time',
               existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Omitir el cambio de tipo de quantity por ahora
    # op.alter_column('task', 'quantity',
    #            existing_type=sa.Integer(),
    #            type_=sa.VARCHAR(),
    #            existing_nullable=True)
    op.add_column('order', sa.Column('status_tmp', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # Remover timezone de programming_task
    op.alter_column('programming_task', 'start_time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('programming_task', 'end_time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###
