"""add_quality_manual_and_chapters

Revision ID: c24f6db028b0
Revises: b743835ec205
Create Date: 2026-01-28 09:17:16.817007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c24f6db028b0'
down_revision: Union[str, Sequence[str], None] = 'b743835ec205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_manual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_manual_id'), 'quality_manual', ['id'], unique=False)
    op.create_index(op.f('ix_quality_manual_name'), 'quality_manual', ['name'], unique=True)
    op.drop_table('order_surplus')
    op.drop_column('order', 'is_hidden')
    op.add_column('qc_manual', sa.Column('quality_manual_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_qc_manual_name'), table_name='qc_manual')
    op.create_index(op.f('ix_qc_manual_quality_manual_id'), 'qc_manual', ['quality_manual_id'], unique=False)
    op.create_foreign_key(None, 'qc_manual', 'quality_manual', ['quality_manual_id'], ['id'], ondelete='CASCADE')
    op.drop_column('qc_manual', 'name')
    op.drop_column('qc_manual', 'content')
    op.drop_column('qc_manual', 'version')
    op.add_column('test_record', sa.Column('code_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('test_record_catalog_test_fkey'), 'test_record', type_='foreignkey')
    op.create_foreign_key(None, 'test_record', 'code', ['code_id'], ['id'])
    op.drop_column('test_record', 'catalog_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_record', sa.Column('catalog_test', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'test_record', type_='foreignkey')
    op.create_foreign_key(op.f('test_record_catalog_test_fkey'), 'test_record', 'catalog_test', ['catalog_test'], ['id'])
    op.drop_column('test_record', 'code_id')
    op.add_column('qc_manual', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('qc_manual', sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('qc_manual', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'qc_manual', type_='foreignkey')
    op.drop_index(op.f('ix_qc_manual_quality_manual_id'), table_name='qc_manual')
    op.create_index(op.f('ix_qc_manual_name'), 'qc_manual', ['name'], unique=False)
    op.drop_column('qc_manual', 'quality_manual_id')
    op.add_column('order', sa.Column('is_hidden', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('order_surplus',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lote', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('original_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('received_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('surplus', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lote'], ['order.lote'], name=op.f('order_surplus_lote_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_surplus_pkey'))
    )
    op.drop_index(op.f('ix_quality_manual_name'), table_name='quality_manual')
    op.drop_index(op.f('ix_quality_manual_id'), table_name='quality_manual')
    op.drop_table('quality_manual')
    # ### end Alembic commands ###
