"""update_schema

Revision ID: c2a8d8ff0b4a
Revises: 000621745134
Create Date: 2026-03-13 09:11:13.544043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2a8d8ff0b4a'
down_revision: Union[str, Sequence[str], None] = '000621745134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('sup_record_stopwatch')]
    
    if 'real_start_time' not in columns:
        op.add_column('sup_record_stopwatch', sa.Column('real_start_time', sa.DateTime(), nullable=True))
    if 'real_end_time' not in columns:
        op.add_column('sup_record_stopwatch', sa.Column('real_end_time', sa.DateTime(), nullable=True))
        
    op.alter_column('sup_record_stopwatch', 'creation_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    
    # Check sup_stopwatch as well for robustness
    stopwatch_columns = [col['name'] for col in inspector.get_columns('sup_stopwatch')]
    
    if 'real_start_time' in stopwatch_columns:
        op.alter_column('sup_stopwatch', 'real_start_time',
                existing_type=postgresql.TIMESTAMP(timezone=True),
                type_=sa.DateTime(),
                existing_nullable=True)
    if 'real_end_time' in stopwatch_columns:
        op.alter_column('sup_stopwatch', 'real_end_time',
                existing_type=postgresql.TIMESTAMP(timezone=True),
                type_=sa.DateTime(),
                existing_nullable=True)
    if 'created_at' in stopwatch_columns:
        op.alter_column('sup_stopwatch', 'created_at',
                existing_type=postgresql.TIMESTAMP(timezone=True),
                type_=sa.DateTime(),
                existing_nullable=True)
    if 'updated_at' in stopwatch_columns:
        op.alter_column('sup_stopwatch', 'updated_at',
                existing_type=postgresql.TIMESTAMP(timezone=True),
                type_=sa.DateTime(),
                existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sup_stopwatch', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('sup_stopwatch', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('sup_stopwatch', 'real_end_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('sup_stopwatch', 'real_start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('sup_record_stopwatch', 'creation_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('sup_record_stopwatch', 'real_end_time')
    op.drop_column('sup_record_stopwatch', 'real_start_time')
    # ### end Alembic commands ###
