"""new table stopwatch-timer

Revision ID: c313d3f26cc8
Revises: c8c3a2e3d749
Create Date: 2025-11-18 14:21:06.983223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c313d3f26cc8'
down_revision: Union[str, Sequence[str], None] = 'c8c3a2e3d749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    timerstatus = sa.Enum('running', 'paused', 'stopped', name='timerstatus')
    timerstatus.create(op.get_bind(), checkfirst=True)
    op.drop_table('stopwatch_timer')
    op.add_column('stopwatch', sa.Column('status', timerstatus, server_default=sa.text("'stopped'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stopwatch', 'status')
    timerstatus = sa.Enum('running', 'paused', 'stopped', name='timerstatus')
    timerstatus.drop(op.get_bind())
    op.create_table('stopwatch_timer',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('running', 'paused', 'stopped', name='timerstatus'), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('accumulated_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_from_programming', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('stopwatch_timer_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stopwatch_timer_pkey'))
    )
    # ### end Alembic commands ###
