"""add_options_to_catalog_test

Revision ID: c3dec41cf904
Revises: 46b9d6e475b5
Create Date: 2025-12-22 09:07:05.248232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3dec41cf904'
down_revision: Union[str, Sequence[str], None] = '46b9d6e475b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_test', sa.Column('options', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_test', 'options')
    # ### end Alembic commands ###
