"""make_lote_unique_in_test

Revision ID: c4812b0ecaa0
Revises: d903849dc362
Create Date: 2025-12-23 08:53:23.631180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4812b0ecaa0'
down_revision: Union[str, Sequence[str], None] = 'd903849dc362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove duplicate `lote` values keeping one row per `lote` before
    # creating the unique constraint. Uses `ctid` to target duplicate
    # physical rows and `ROW_NUMBER()` to keep a single row per group.
    bind = op.get_bind()
    bind.execute(
        sa.text(
            """
            DELETE FROM test
            WHERE ctid IN (
                SELECT ctid FROM (
                    SELECT ctid, ROW_NUMBER() OVER (PARTITION BY lote ORDER BY ctid) AS rn
                    FROM test WHERE lote IS NOT NULL
                ) t WHERE t.rn > 1
            )
            """
        )
    )

    op.create_unique_constraint(None, 'test', ['lote'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='unique')
    # ### end Alembic commands ###
