"""add_full_name_and_cargo_to_users

Revision ID: c6a6cc1e9d8d
Revises: 105776b15713
Create Date: 2026-02-02 09:56:26.807594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a6cc1e9d8d'
down_revision: Union[str, Sequence[str], None] = '105776b15713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cargo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cargo')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
