"""add stopwatch_timer table

Revision ID: c8c3a2e3d749
Revises: 3714b5e23592
Create Date: 2025-11-18 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = 'c8c3a2e3d749'
down_revision: Union[str, Sequence[str], None] = '3714b5e23592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    timerstatus_enum = sa.Enum('RUNNING', 'PAUSED', 'STOPPED', name='timerstatus')
    op.create_table('stopwatch_timer',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('task_id', UUID(as_uuid=True), nullable=False),
    sa.Column('status', timerstatus_enum, nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('accumulated_duration', sa.Float(), nullable=False),
    sa.Column('is_from_programming', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('stopwatch', sa.Column('status', timerstatus_enum, nullable=False, server_default='STOPPED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stopwatch', 'status')
    op.drop_table('stopwatch_timer')
    timerstatus_enum = sa.Enum('RUNNING', 'PAUSED', 'STOPPED', name='timerstatus')
    timerstatus_enum.drop(op.get_bind())
    # ### end Alembic commands ###
