"""restore_is_hidden_to_order

Revision ID: ccf2a51316e6
Revises: 3394ae84531b
Create Date: 2026-01-29 11:34:37.201675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf2a51316e6'
down_revision: Union[str, Sequence[str], None] = '3394ae84531b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_surplus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lote', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('original_quantity', sa.Float(), nullable=False),
    sa.Column('received_quantity', sa.Float(), nullable=False),
    sa.Column('surplus', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lote'], ['order.lote'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'is_hidden')
    op.drop_table('order_surplus')
    # ### end Alembic commands ###
