"""Change accumulated_duration to Float in Stopwatch and RecordStopwatch models and schemas

Revision ID: d0c13ee0ed78
Revises: 303638fea529
Create Date: 2025-10-31 15:10:42.499022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c13ee0ed78'
down_revision: Union[str, Sequence[str], None] = '303638fea529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
