"""add document_name to users

Revision ID: d903849dc362
Revises: 0835a60fe27f
Create Date: 2025-12-22 15:14:32.864865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd903849dc362'
down_revision: Union[str, Sequence[str], None] = '0835a60fe27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first to avoid NOT NULL violation on existing rows
    op.add_column('qc_manual', sa.Column('created_by', sa.String(), nullable=True))
    # Backfill existing NULL values with a safe default (change if needed)
    op.execute("UPDATE qc_manual SET created_by = 'system' WHERE created_by IS NULL")
    # Now enforce NOT NULL constraint
    op.alter_column('qc_manual', 'created_by', nullable=False)
    op.add_column('users', sa.Column('document_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'document_name')
    op.drop_column('qc_manual', 'created_by')
    # ### end Alembic commands ###
