"""add tracking fields to test table

Revision ID: dc283877710f
Revises: 979439832514
Create Date: 2025-12-30 10:05:14.802931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc283877710f'
down_revision: Union[str, Sequence[str], None] = '979439832514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('performed_by', sa.String(), nullable=True))
    op.add_column('test', sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('test', sa.Column('approved_by', sa.String(), nullable=True))
    op.add_column('test', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'approved_at')
    op.drop_column('test', 'approved_by')
    op.drop_column('test', 'performed_at')
    op.drop_column('test', 'performed_by')
    # ### end Alembic commands ###
