"""Add accounting role

Revision ID: e55475148062
Revises: f70bc6c3962d
Create Date: 2025-10-21 11:53:18.006409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55475148062'
down_revision: Union[str, Sequence[str], None] = 'f70bc6c3962d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole ADD VALUE 'ACCOUNTING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Downgrading by removing a value from an ENUM is not directly supported
    # and can be complex. If needed, this should be implemented manually.
    pass
    # ### end Alembic commands ###
