"""quality test workflow

Revision ID: ebe052fa06aa
Revises: dc283877710f
Create Date: 2026-01-08 10:05:55.831699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebe052fa06aa'
down_revision: Union[str, Sequence[str], None] = 'dc283877710f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Robust ENUM creation
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'questiontype') THEN
                CREATE TYPE questiontype AS ENUM ('open', 'close', 'both');
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'teststatus') THEN
                CREATE TYPE teststatus AS ENUM ('done', 'undone', 'accepted', 'pending');
            END IF;
        END $$;
    """)

    # Drop old table first
    op.drop_table('test')

    op.create_table('catalog_test_question',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_test_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('specification', sa.String(), nullable=True),
    sa.Column('type', postgresql.ENUM('open', 'close', 'both', name='questiontype', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['catalog_test_id'], ['catalog_test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('test_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lote', sa.Integer(), nullable=False),
    sa.Column('catalog_test', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('done', 'undone', 'accepted', 'pending', name='teststatus', create_type=False), nullable=False),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_test'], ['catalog_test.id'], ),
    sa.ForeignKeyConstraint(['lote'], ['order.lote'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('test_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_record_id', sa.UUID(), nullable=False),
    sa.Column('catalog_test_id', sa.UUID(), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_test_id'], ['catalog_test.id'], ),
    sa.ForeignKeyConstraint(['test_record_id'], ['test_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Rename 'test' to 'name'
    op.alter_column('catalog_test', 'test', new_column_name='name')
    
    # Add 'chapter' and 'status' with defaults to handle existing data
    op.add_column('catalog_test', sa.Column('chapter', sa.String(), nullable=False, server_default='General'))
    op.add_column('catalog_test', sa.Column('status', sa.Boolean(), nullable=False, server_default='true'))
    
    # Drop other old columns
    op.drop_column('catalog_test', 'options')
    op.drop_column('catalog_test', 'type')
    op.drop_column('catalog_test', 'manual_section_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Robust ENUM creation
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'teststatus') THEN
                CREATE TYPE teststatus AS ENUM ('done', 'undone', 'accepted', 'pending');
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'type') THEN
                CREATE TYPE type AS ENUM ('open', 'close', 'both');
            END IF;
        END $$;
    """)

    op.drop_table('test_results')
    op.drop_table('test_record')
    op.drop_table('catalog_test_question')

    op.add_column('catalog_test', sa.Column('manual_section_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('catalog_test', sa.Column('type', postgresql.ENUM('open', 'close', 'both', name='type', create_type=False), autoincrement=False, nullable=False))
    op.add_column('catalog_test', sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    
    # Symmetrical rename and drop
    op.alter_column('catalog_test', 'name', new_column_name='test')
    op.drop_column('catalog_test', 'status')
    op.drop_column('catalog_test', 'chapter')

    op.create_table('test',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lote', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('done', 'undone', 'accepted', 'pending', name='teststatus', create_type=False), autoincrement=False, nullable=False),
    sa.Column('results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('performed_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('performed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lote'], ['order.lote'], name=op.f('test_lote_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test_pkey'))
    )
    # ### end Alembic commands ###
