"""Change accumulated_duration to Float in Stopwatch and RecordStopwatch models

Revision ID: ee9ab5e60be0
Revises: 72eeaa29fd61
Create Date: 2025-10-31 13:49:59.820394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9ab5e60be0'
down_revision: Union[str, Sequence[str], None] = '72eeaa29fd61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record_stopwatch', 'accumulated_duration',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('stopwatch', 'accumulated_duration',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stopwatch', 'accumulated_duration',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('record_stopwatch', 'accumulated_duration',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
