"""Migrate CodeVerification to boolean

Revision ID: f24335743296
Revises: 06b228757bc0
Create Date: 2026-04-08 08:44:11.920284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f24335743296'
down_revision: Union[str, Sequence[str], None] = '06b228757bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_verification')
    op.drop_table('code_catalog')
    op.add_column('code', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code', 'is_verified')
    op.create_table('code_catalog',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('code_catalog_pkey'))
    )
    op.create_table('code_verification',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('codeId', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['codeId'], ['code.id'], name=op.f('code_verification_codeId_fkey')),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('code_verification_userId_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('code_verification_pkey'))
    )
    # ### end Alembic commands ###
