"""update_catalog_test_and_questions

Revision ID: f95c7a5f15ce
Revises: c24f6db028b0
Create Date: 2026-01-28 11:46:03.463059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95c7a5f15ce'
down_revision: Union[str, Sequence[str], None] = 'c24f6db028b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_test', sa.Column('quality_manual_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_catalog_test_chapter_id'), table_name='catalog_test')
    op.create_index(op.f('ix_catalog_test_quality_manual_id'), 'catalog_test', ['quality_manual_id'], unique=False)
    op.drop_constraint(op.f('fk_catalog_test_chapter_id'), 'catalog_test', type_='foreignkey')
    op.create_foreign_key(None, 'catalog_test', 'quality_manual', ['quality_manual_id'], ['id'], ondelete='SET NULL')
    op.drop_column('catalog_test', 'chapter_id')
    op.add_column('catalog_test_question', sa.Column('chapter_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_catalog_test_question_chapter_id'), 'catalog_test_question', ['chapter_id'], unique=False)
    op.create_foreign_key(None, 'catalog_test_question', 'qc_manual_chapter', ['chapter_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalog_test_question', type_='foreignkey')
    op.drop_index(op.f('ix_catalog_test_question_chapter_id'), table_name='catalog_test_question')
    op.drop_column('catalog_test_question', 'chapter_id')
    op.add_column('catalog_test', sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'catalog_test', type_='foreignkey')
    op.create_foreign_key(op.f('fk_catalog_test_chapter_id'), 'catalog_test', 'qc_manual_chapter', ['chapter_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_catalog_test_quality_manual_id'), table_name='catalog_test')
    op.create_index(op.f('ix_catalog_test_chapter_id'), 'catalog_test', ['chapter_id'], unique=False)
    op.drop_column('catalog_test', 'quality_manual_id')
    # ### end Alembic commands ###
