"""add missing fields to task and sync all models

Revision ID: ff84b38e27cc
Revises: 9b4e98293d74
Create Date: 2025-07-19 10:05:55.519074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff84b38e27cc'
down_revision: Union[str, Sequence[str], None] = '9b4e98293d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('unit', sa.String(), nullable=True))
    op.add_column('task', sa.Column('type', sa.String(), nullable=True))
    op.add_column('task', sa.Column('activity', sa.String(), nullable=True))
    op.add_column('task', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'description')
    op.drop_column('task', 'activity')
    op.drop_column('task', 'type')
    op.drop_column('task', 'unit')
    # ### end Alembic commands ###
