from typing import List
from sqlalchemy.orm import Session
from app.modules.available.models.availableModel import Available
from app.modules.available.schemas.available import AvailableCreate, AvailableUpdate


def create_available(db: Session, available: AvailableCreate) -> Available:
    db_item = Available(**available.dict())
    db.add(db_item)
    db.commit()
    db.refresh(db_item)
    return db_item


def create_available_bulk(db: Session, items: List[AvailableCreate]) -> List[Available]:
    objs = [Available(**item.dict()) for item in items]
    # Add all and commit once for efficiency
    db.add_all(objs)
    db.commit()
    # refresh to populate autogenerated fields
    for o in objs:
        db.refresh(o)
    return objs


def get_available(db: Session, available_id) -> Available | None:
    return db.query(Available).filter(Available.id == available_id).first()


def get_available_list(db: Session, skip: int = 0, limit: int = 100) -> List[Available]:
    return db.query(Available).offset(skip).limit(limit).all()


def update_available(db: Session, available_id, available_update: AvailableUpdate) -> Available | None:
    db_item = db.query(Available).filter(Available.id == available_id).first()
    if not db_item:
        return None
    update_data = available_update.dict(exclude_unset=True)
    for field, value in update_data.items():
        setattr(db_item, field, value)
    db.commit()
    db.refresh(db_item)
    return db_item


def delete_available(db: Session, available_id) -> bool:
    db_item = db.query(Available).filter(Available.id == available_id).first()
    if not db_item:
        return False
    db.delete(db_item)
    db.commit()
    return True


def delete_all_available(db: Session) -> int:
    """
    Delete all Available records.
    Returns the number of deleted rows.
    """
    deleted = db.query(Available).delete(synchronize_session=False)
    db.commit()
    return deleted
